import Image from "next/image";
import "./globals.css";
import { Inter } from "next/font/google";
import logo from "@/assets/footer-brand.svg";
import Footer from "./components/footer";

// Initialization for ES Users

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={[inter.className]}>
        <header className="py-2 shadow-md shadow-gray-600">
          <nav className="flex container mx-auto justify-between items-center">
            <Image src={logo} alt="logo" width="80" height="80" />
            <div>
              <input type="text" placeholder="Searching" />
            </div>
          </nav>
        </header>
        {children}
        <footer className="py-2 bg-black mt-5">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
